"use client";
import Link from 'next/link';
import {useState} from 'react';
import {useLanguage} from '@/components/language-provider';
import {Button} from '@/components/ui/button';
import {NativeSelect} from '@/components/ui/native-select';
import {FormattedNumberInput} from '@/components/formatted-number-input';
import {DatePicker} from '@/components/date-picker';
import {ForecastAccountAssignment} from '@/components/forecast-account-assignment';
import type {ToolsController} from '@/components/transaction-tools-panel';
import type {PreferenceResource} from '@/hooks/use-workspace-preferences';
import {useOwnerResource} from '@/hooks/use-owner-resource';
import {formatDate,formatMoney} from '@/lib/format';
import {depositToday} from '@/lib/deposit-interest';
import {expenses,type Entry} from '@/lib/finance';
import type {PlanningData} from '@/lib/planning';
import type {ExpensePlan} from '@/lib/expense-plans';
import type {MarketData} from '@/lib/market';
import {availableToSpend,emptyDailyPlan,dueReminders,financialHealth,templateFromRecord,entryFromTemplate,type DailyPlan,type ReminderSettings} from '@/lib/daily-finance';
const noStatus:Array<{account_id:string;name:string;end_date:string|null;valid:boolean}> = [];
export function DailyFinancePanel({data,tools,preferences,plans,market,currency,owner,demo,revision}:{data:PlanningData;tools:ToolsController;preferences:PreferenceResource;plans:ExpensePlan[];market:MarketData|null;currency:string;owner:string|null;demo:boolean;revision:number}){
 const {t,locale}=useLanguage(),today=depositToday();const [through,setThrough]=useState(today.slice(0,7)+'-'+String(new Date(Date.UTC(Number(today.slice(0,4)),Number(today.slice(5,7)),0)).getUTCDate()));
 const status=useOwnerResource('/api/reconciliation/status',owner,!demo,revision,noStatus);
 const settings=preferences.data.preferences.find(p=>p.key==='daily_plan')?.data??emptyDailyPlan;
 const allowance=availableToSpend(data,tools.data.assignments,plans,settings,today,through);
 const [checkedAt]=useState(()=>Date.now());const health=financialHealth(data.records,market,currency,checkedAt);
 return <><section className="panel tools-panel"><div className="panel-title"><div><h2>{t('Available to spend')}</h2><p className="muted">{t('An estimate from spending accounts after unpaid bills, remaining budgets, goal reservations and your cash buffer. Expected income is shown separately.')}</p></div><label>{t('Show through')}<DatePicker value={through} min={today} max={new Date(Date.UTC(Number(today.slice(0,4)),Number(today.slice(5,7)),0)).toISOString().slice(0,10)} onChange={setThrough}/></label></div>
 {allowance.issues.map(issue=><p className="error" key={issue}>{t(issue)}</p>)}
 <div className="planning-cards">{allowance.rows.map(row=><article className="daily-allowance" key={row.account.id}><h3>{row.account.name}</h3><strong>{row.available===null?'—':formatMoney(row.available,row.account.currency,locale)}</strong><p className="muted">{t('Estimate, not a bank guarantee.')}</p><dl><div><dt>{t('Current balance')}</dt><dd>{formatMoney(row.account.amount,row.account.currency,locale)}</dd></div><div><dt>{t('Unpaid bills')}</dt><dd>{formatMoney(row.bills,row.account.currency,locale)}</dd></div><div><dt>{t('Goal reservations')}</dt><dd>{formatMoney(row.reserves,row.account.currency,locale)}</dd></div><div><dt>{t('Remaining budgets after bill overlap')}</dt><dd>{formatMoney(row.budgets,row.account.currency,locale)}</dd></div><div><dt>{t('Cash buffer')}</dt><dd>{formatMoney(row.buffer,row.account.currency,locale)}</dd></div><div><dt>{t('Expected income')}</dt><dd>{formatMoney(row.expectedIncome,row.account.currency,locale)}</dd></div><div><dt>{t('Forecast including expected income')}</dt><dd>{row.available===null?'—':formatMoney(row.forecast,row.account.currency,locale)}</dd></div></dl>{row.reasons.map(reason=><p className="error" key={reason}>{t(reason)}</p>)}<details><summary>{t('Included bills and income')}</summary><ul>{row.events.map(e=><li key={e.key}>{e.name} · {formatDate(e.date,locale)} · {formatMoney(e.amount,row.account.currency,locale)}</li>)}</ul></details></article>)}</div>
 {!allowance.rows.length&&<p>{t('Add a spending cash account to calculate an allowance.')}</p>}
 <details><summary>{t('Set budgets and cash buffers')}</summary><BudgetSettings key={JSON.stringify(settings)} initial={settings} data={data} plans={plans} preferences={preferences}/></details>
 <details><summary>{t('Assign scheduled bills and income')}</summary><div className="daily-settings">{data.records.filter(r=>r.frequency!=='Once').map(record=><ForecastAccountAssignment key={record.id+JSON.stringify(tools.data.assignments.find(a=>a.record_id===record.id))} record={record} accounts={data.records.filter(r=>r.kind==='Cash')} assignment={tools.data.assignments.find(a=>a.record_id===record.id)} today={today} tools={tools}/>)}</div></details>
 <p className="muted">{t('Budgets reserve their remaining monthly allowance even when the selected date is earlier. Investment cash is excluded. Missing obligations make the result incomplete.')}</p>
 </section><section className="panel tools-panel"><h2>{t('Financial data health')}</h2><ul className="tool-list">{health.map(issue=><li key={issue.key}><span><strong>{issue.name}</strong> · {t(issue.message)}</span><Link href={issue.href}>{t('Review')}</Link></li>)}{status.data.filter(s=>!s.valid).map(s=><li key={s.account_id}><span>{s.name} · {t(s.end_date?'The statement needs another review.':'No reconciled statement yet.')}</span><Link href="/accounts">{t('Review')}</Link></li>)}</ul>{status.error&&<p role="alert">{t(status.error)} <Button onClick={status.retry}>{t('Retry')}</Button></p>}{!health.length&&!status.error&&!status.loading&&!status.data.some(s=>!s.valid)&&<p>{t('No issues found in these checks. This is not a complete audit.')}</p>}</section></>;
}
function BudgetSettings({initial,data,plans,preferences}:{initial:DailyPlan;data:PlanningData;plans:ExpensePlan[];preferences:PreferenceResource}){
 const {t}=useLanguage();const [draft,setDraft]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const accounts=data.records.filter(r=>r.kind==='Cash'&&!r.is_investment&&!r.holding_account_id);
 return <form className="record-form daily-settings" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await preferences.save({key:'daily_plan',data:draft});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><fieldset disabled={busy} className="tracker-fields">
 {accounts.map(a=><label key={a.id}>{a.name} · {t('Cash buffer')} · {a.currency}<FormattedNumberInput required={false} value={draft.buffers[a.id]??0} onValueChange={n=>setDraft({...draft,buffers:{...draft.buffers,[a.id]:n}})}/></label>)}
 {plans.map(plan=>{const binding=draft.budgets.find(b=>b.plan_id===plan.id);return <div className="daily-budget" key={plan.id}><label>{plan.name} · {plan.currency}<NativeSelect value={binding?.account_id??''} onChange={e=>setDraft({...draft,budgets:[...draft.budgets.filter(b=>b.plan_id!==plan.id),...(e.target.value?[{plan_id:plan.id,account_id:e.target.value,schedule_ids:[]}]:[])]})}><option value="">{t('Assign budget account')}</option>{accounts.filter(a=>a.currency===plan.currency).map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</NativeSelect></label>{binding&&<><p>{t('Bills already included in this budget')}</p>{data.records.filter(r=>expenses.includes(r.kind)&&r.frequency!=='Once').map(r=><label className="daily-checkbox" key={r.id}><input type="checkbox" checked={binding.schedule_ids.includes(r.id)} onChange={e=>setDraft({...draft,budgets:draft.budgets.map(b=>({...b,schedule_ids:b.plan_id===plan.id?(e.target.checked?[...b.schedule_ids,r.id]:b.schedule_ids.filter(id=>id!==r.id)):b.schedule_ids.filter(id=>id!==r.id)}))})}/>{r.name}</label>)}</>}</div>;})}</fieldset>
 {error&&<p className="error" role="alert">{t(error)}</p>}<Button disabled={busy}>{t(busy?'Saving…':'Save')}</Button></form>;
}
export function ReminderPanel({data,preferences}:{data:PlanningData;preferences:PreferenceResource}){
 const {t,locale}=useLanguage(),today=depositToday();const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 const settings:ReminderSettings=preferences.data.preferences.find(p=>p.key==='reminders')?.data??{enabled:true,days_ahead:7,snoozed:[]};
 const reminders=dueReminders(data,settings,today);
 async function save(next:ReminderSettings){setBusy(true);setError('');try{await preferences.save({key:'reminders',data:next});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <details className="panel tools-panel reminders-panel"><summary><h2>{t('Reminders')}</h2></summary><p className="muted">{t('Shown when you open the app. No email or push messages are sent, and reminders never record payments.')}</p>
 <ul className="tool-list">{reminders.map(item=><li key={item.key}><div><strong>{item.record.name}</strong><p>{formatDate(item.date,locale)} · {formatMoney(item.record.amount,item.record.currency,locale)} · {t(item.overdue?'Overdue':'Upcoming')}</p></div><div className="entry-actions"><Link href="/upcoming">{t('Review')}</Link><Button variant="outline" disabled={busy} onClick={()=>void save({...settings,snoozed:[...settings.snoozed.filter(s=>s.key!==item.key&&s.until>today).slice(-499),{key:item.key,until:new Date(Date.parse(today+'T00:00:00Z')+86400000).toISOString().slice(0,10)}]})}>{t('Snooze until tomorrow')}</Button></div></li>)}</ul>{settings.enabled&&!reminders.length&&<p>{t('No reminders in this period.')}</p>}{error&&<p role="alert" className="error">{t(error)}</p>}</details>;
}
export function QuickEntries({data,preferences,onEntry,currencies}:{data:PlanningData;preferences:PreferenceResource;onEntry:(entry:Entry)=>void;currencies:string[]}){
 const {t,locale}=useLanguage();const [selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const items=preferences.data.preferences.find(p=>p.key==='entry_templates')?.data.items??[];
 const candidates=data.records.filter(r=>templateFromRecord(r,r.id));
 async function save(next:typeof items){setBusy(true);setError('');try{await preferences.save({key:'entry_templates',data:{items:next}});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel tools-panel"><h2>{t('Quick entries')}</h2><p className="muted">{t('Open a saved template in the normal form. Review it before saving a new transaction.')}</p><ul className="tool-list">{items.map(item=><li key={item.id}><span>{item.name} · {formatMoney(item.amount,item.currency,locale)}</span><div className="entry-actions"><Button onClick={()=>{if(!currencies.includes(item.currency)){setError('This template currency is no longer preferred. Add it in Settings before using the template.');return;}setError('');onEntry(entryFromTemplate(item,crypto.randomUUID(),depositToday(),data.records,data.categories.map(c=>c.id)));}}>{t('Use template')}</Button><Button variant="ghost" disabled={busy} onClick={()=>void save(items.filter(i=>i.id!==item.id))}>{t('Remove')}</Button></div></li>)}</ul>
 <div className="inline-tool-form"><label>{t('Save a recent entry as a template')}<NativeSelect disabled={busy} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">{t('Choose a transaction')}</option>{candidates.map(r=><option value={r.id} key={r.id}>{r.name} · {formatMoney(r.amount,r.currency,locale)}</option>)}</NativeSelect></label><Button disabled={busy||!selected||items.length>=30} onClick={()=>{const record=candidates.find(r=>r.id===selected);if(record){const template=templateFromRecord(record,crypto.randomUUID());if(template)void save([...items,template]);}}}>{t('Save template')}</Button></div>{!candidates.length&&<p className="muted">{t('Templates can be created from recent ordinary transactions in Income & expenses.')}</p>}{error&&<p role="alert" className="error">{t(error)}</p>}</section>;
}
