"use client";
import type { MarketData } from '@/lib/market';
import { FinancialReportExport } from '@/components/financial-report-export';
import { useUnsavedNavigation } from '@/components/discard-changes';
import {ImportProfiles} from '@/components/import-profiles';
import type {PreferenceResource} from '@/hooks/use-workspace-preferences';
import { useState } from 'react';
import { Download, FileSpreadsheet } from 'lucide-react';
import { useLanguage } from '@/components/language-provider';
import { Button } from '@/components/ui/button';
import { NativeSelect } from '@/components/ui/native-select';
import { Checkbox } from '@/components/ui/checkbox';
import { parseCSV,mapCSV,type ColumnMapping } from '@/lib/csv';
import { formatDate,formatMoney,formatNumber } from '@/lib/format';
import type { Entry } from '@/lib/finance';
export function DataTools({records,onSaved,demo,preferences,market,currency}:{currency?:string;market?:MarketData|null;preferences:PreferenceResource;records:Entry[];onSaved:()=>void;demo:boolean}){
 const {t,locale}=useLanguage();const [text,setText]=useState(''),[delimiter,setDelimiter]=useState(','),[accountId,setAccountId]=useState('');const [mapping,setMapping]=useState<ColumnMapping>({name:0,date:1,amount:2,notes:-1,sourceId:-1,dateFormat:'iso',decimal:'.'});const [excluded,setExcluded]=useState<number[]>([]);const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [batchId,setBatchId]=useState<string|null>(null);
 const confirmation=useUnsavedNavigation(!!text);
 let headers:string[]=[],rows:ReturnType<typeof mapCSV>=[],parseError='';
 if(text)try{const parsed=parseCSV(text,delimiter);headers=parsed[0]??[];rows=mapCSV(parsed,mapping);}catch(reason){parseError=(reason as Error).message;}
 const account=records.find(record=>record.id===accountId&&record.kind==='Cash');
 const changeMapping=(next:ColumnMapping)=>{setMapping(next);setExcluded([]);setMessage('');setBatchId(null);};
 return <section id="data-tools" className="panel tools-panel data-settings"><h2>{t('Import and backup')}</h2><section className="data-backup-section"><div className="data-backup-actions"><FinancialReportExport demo={demo} market={market} currency={currency}/><Button asChild variant="outline"><a href="/api/backup" aria-disabled={demo} onClick={event=>{if(demo)event.preventDefault();}}><Download size={18} aria-hidden="true"/>{t('Download complete backup')}</a></Button><Button asChild variant="outline"><a href="/api/backup?format=csv" aria-disabled={demo} onClick={event=>{if(demo)event.preventDefault();}}><FileSpreadsheet size={18} aria-hidden="true"/>{t('Export records as CSV')}</a></Button></div><p className="muted">{t('CSV exports are for reference. Backup restore is not available yet.')}</p></section><section className="data-import-section"><h3>{t('Import transactions')}</h3><p className="muted">{t('Keep a backup before importing. Reimporting the same transactions safely skips duplicates.')}</p>{demo&&<p>{t('Sign in to import or export account data.')}</p>}
 <div className="data-import-fields"><label className="data-file-field">{t('CSV file')}<input type="file" accept=".csv,text/csv" disabled={busy||demo} onChange={async event=>{const file=event.target.files?.[0];if(!file)return;setError('');setMessage('');setExcluded([]);setBatchId(null);if(file.size>2_000_000){setText('');setError('File is too large.');return;}try{setText(await file.text());}catch{setError('Could not read the file.');}}}/></label><label>{t('Cash account')}<NativeSelect disabled={busy} value={accountId} onChange={event=>{setAccountId(event.target.value);setBatchId(null);}}><option value="">{t('Select account')}</option>{records.filter(record=>record.kind==='Cash').map(record=><option key={record.id} value={record.id}>{record.name} · {record.currency}</option>)}</NativeSelect></label><label>{t('Delimiter')}<NativeSelect disabled={busy} value={delimiter} onChange={event=>{setDelimiter(event.target.value);setExcluded([]);setBatchId(null);}}><option value=",">{t('Comma')}</option><option value=";">{t('Semicolon')}</option><option value={'\t'}>{t('Tab')}</option></NativeSelect></label></div>
 <ImportProfiles mapping={mapping} delimiter={delimiter} apply={(next,separator)=>{changeMapping(next);setDelimiter(separator);}} preferences={preferences}/>
 {!!text&&<><div className="review-grid">{(['name','date','amount','notes','sourceId'] as const).map(key=><label key={key}>{t(({name:'Name',date:'Date',amount:'Amount',notes:'Notes',sourceId:'Source transaction ID'})[key])}<NativeSelect disabled={busy} value={mapping[key]} onChange={event=>changeMapping({...mapping,[key]:Number(event.target.value)})}>{(key==='notes'||key==='sourceId')&&<option value={-1}>{t('None')}</option>}{headers.map((header,index)=><option value={index} key={index}>{header}</option>)}</NativeSelect></label>)}<label>{t('Date format')}<NativeSelect disabled={busy} value={mapping.dateFormat} onChange={event=>changeMapping({...mapping,dateFormat:event.target.value as ColumnMapping['dateFormat']})}><option value="iso">YYYY-MM-DD</option><option value="dmy">DD/MM/YYYY</option><option value="mdy">MM/DD/YYYY</option></NativeSelect></label><label>{t('Decimal separator')}<NativeSelect disabled={busy} value={mapping.decimal} onChange={event=>changeMapping({...mapping,decimal:event.target.value as '.'|','})}><option value=".">.</option><option value=",">,</option></NativeSelect></label></div><p className="muted">{t('Map a stable source transaction ID when available. Without IDs, overlapping statements with identical purchases can be ambiguous; review duplicates before importing.')}</p><p>{t('Positive amounts are income; negative amounts are expenses. All rows use the selected account currency.')}</p>
 {parseError?<p className="error" role="alert">{t(parseError)}</p>:<><p>{t('{count} selected transactions',{count:formatNumber(rows.length-excluded.length,locale,0)})}</p><div className="table-scroll import-preview"><table><thead><tr><th>{t('Import')}</th><th>{t('Name')}</th><th>{t('Date')}</th><th>{t('Amount')}</th><th>{t('Category')}</th></tr></thead><tbody>{rows.map((row,index)=><tr key={index}><td><Checkbox disabled={busy} checked={!excluded.includes(index)} aria-label={t('Import {name}',{name:row.name})} onCheckedChange={checked=>{setExcluded(checked?excluded.filter(value=>value!==index):[...excluded,index]);setBatchId(null);}}/></td><td>{row.name}</td><td>{formatDate(row.date,locale)}</td><td>{account?formatMoney(row.amount,account.currency,locale):formatNumber(row.amount,locale,0)}</td><td>{t(row.amount>0?'Other income':'Other expense')}</td></tr>)}</tbody></table></div><Button disabled={busy||demo||!account||rows.length===excluded.length} onClick={async()=>{const newBatchId=crypto.randomUUID();if(!batchId)setBatchId(newBatchId);setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({batch_id:batchId??newBatchId,account_id:accountId,rows:rows.map((row,index)=>({...row,selected:!excluded.includes(index)}))})});const result=await response.json() as {error?:string;added:number;skipped:number};if(!response.ok)throw Error(result.error);setMessage(t('Imported {added}; skipped {skipped}.',{added:formatNumber(result.added,locale,0),skipped:formatNumber(result.skipped,locale,0)}));setText('');setBatchId(null);onSaved();}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}}}>{t(busy?'Importing…':'Import selected transactions')}</Button></>}</>}
 {error&&<p className="error" role="alert">{t(error)}</p>}{message&&<p role="status">{message}</p>}
 </section>{confirmation}</section>;
}
