"use client";
import { showSaved } from '@/lib/feedback';
import { ErrorPopup } from '@/components/presentation-foundation/error-popup';
import { BackupRestore } from '@/components/backup-restore';
import type { MarketData } from '@/lib/market';
import { FinancialReportExport } from '@/components/financial-report-export';
import { useUnsavedNavigation } from '@/components/discard-changes';
import {ImportProfiles} from '@/components/import-profiles';
import type {PreferenceResource} from '@/hooks/use-workspace-preferences';
import { useState } from 'react';
import { Download, FileSpreadsheet } from 'lucide-react';
import { InfoHint } from '@/components/presentation-foundation/info-hint';
import { useLanguage } from '@/components/language-provider';
import { Button } from '@/components/ui/button';
import { NativeSelect } from '@/components/ui/native-select';
import { Checkbox } from '@/components/ui/checkbox';
import { parseCSV,mapCSV,guessColumnMapping,guessDelimiter,guessTableMapping,type ColumnMapping } from '@/lib/csv';
import type { StatementFile } from '@/lib/statement-files';
import { formatAccountOption,formatDate,formatMoney,formatNumber } from '@/lib/format';
import type { Entry } from '@/lib/finance';
export function DataTools({records,onSaved,demo,preferences,market,currency,owner}:{owner?:string|null;currency?:string;market?:MarketData|null;preferences:PreferenceResource;records:Entry[];onSaved:()=>void;demo:boolean}){
 const {t,locale}=useLanguage();const [source,setSource]=useState<StatementFile|null>(null),[sheet,setSheet]=useState(0),[delimiter,setDelimiter]=useState(','),[accountId,setAccountId]=useState('');const [mapping,setMapping]=useState<ColumnMapping>({name:0,date:1,amount:2,notes:-1,sourceId:-1,dateFormat:'iso',decimal:'.'});const [excluded,setExcluded]=useState<number[]>([]);const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [batchId,setBatchId]=useState<string|null>(null);
 const confirmation=useUnsavedNavigation(!!source);
 let headers:string[]=[],rows:ReturnType<typeof mapCSV>=[],parseError='';
 // Excel, OFX and QIF files arrive as ready tables; CSV text is split with the chosen delimiter.
 if(source)try{const parsed=source.format==='csv'?parseCSV(source.text,delimiter):source.sheets[sheet]?.rows??[];headers=parsed[0]??[];rows=mapCSV(parsed,mapping);}catch(reason){parseError=(reason as Error).message;}
 const account=records.find(record=>record.id===accountId&&record.kind==='Cash');
 const changeMapping=(next:ColumnMapping)=>{setMapping(next);setExcluded([]);setMessage('');setBatchId(null);};
 return <section id="data-tools" className="panel tools-panel data-settings"><h2>{t('Import and backup')}<InfoHint>{t('CSV exports are for reference. Use a verified JSON backup to restore this account.')}</InfoHint></h2><section className="data-backup-section"><div className="data-backup-actions"><FinancialReportExport demo={demo} market={market} currency={currency}/><Button asChild variant="outline"><a href="/api/backup" aria-disabled={demo} onClick={event=>{if(demo)event.preventDefault();}}><Download size={18} aria-hidden="true"/>{t('Download complete backup')}</a></Button><Button asChild variant="outline"><a href="/api/backup?format=csv" aria-disabled={demo} onClick={event=>{if(demo)event.preventDefault();}}><FileSpreadsheet size={18} aria-hidden="true"/>{t('Export records as CSV')}</a></Button></div></section><BackupRestore demo={demo} owner={owner??null} onSaved={onSaved}/><section className="data-import-section"><h3>{t('Import transactions')}<InfoHint>{t('Keep a backup before importing. Reimporting the same transactions safely skips duplicates.')}</InfoHint></h3>{demo&&<p>{t('Sign in to import or export account data.')}</p>}
 <div className="data-import-fields"><label className="data-file-field">{t('Statement file')}<input type="file" accept=".csv,.tsv,.txt,.xlsx,.xls,.ofx,.qfx,.qif" disabled={busy||demo} onChange={async event=>{const file=event.target.files?.[0];if(!file)return;setError('');setMessage('');setExcluded([]);setBatchId(null);setSource(null);setSheet(0);if(file.size>2_000_000){setError('File is too large.');return;}
 // The readers load only when a file is chosen.
 const reader=await import('@/lib/statement-files').catch(()=>null);if(!reader){setError('Could not read the file.');return;}
 try{const read=await reader.readStatementFile(file.name,new Uint8Array(await file.arrayBuffer()));if(read.format==='csv'){const separator=guessDelimiter(read.text);setDelimiter(separator);try{setMapping(guessColumnMapping(parseCSV(read.text,separator)[0]??[],mapping));}catch{/* Parse errors are shown with the preview. */}}else setMapping(guessTableMapping(read.sheets[0].rows,mapping));setSource(read);}catch(reason){setError((reason as Error).message||'Could not read the file.');}}}/></label><label>{t('Cash account')}<NativeSelect disabled={busy} value={accountId} onChange={event=>{setAccountId(event.target.value);setBatchId(null);}}><option value="">{t('Select account')}</option>{records.filter(record=>record.kind==='Cash').map(record=><option key={record.id} value={record.id}>{formatAccountOption(record,locale)}</option>)}</NativeSelect></label>{source&&source.format!=='csv'?source.sheets.length>1&&<label>{t(source.format==='ofx'||source.format==='qif'?'Statement account':'Sheet')}<NativeSelect disabled={busy} value={sheet} onChange={event=>{const next=Number(event.target.value);setSheet(next);changeMapping(guessTableMapping(source.sheets[next].rows,mapping));}}>{source.sheets.map((item,index)=><option key={index} value={index}>{item.label||'—'}</option>)}</NativeSelect></label>:<label>{t('Delimiter')}<NativeSelect disabled={busy} value={delimiter} onChange={event=>{setDelimiter(event.target.value);setExcluded([]);setBatchId(null);}}><option value=",">{t('Comma')}</option><option value=";">{t('Semicolon')}</option><option value={'\t'}>{t('Tab')}</option></NativeSelect></label>}</div>
 <ImportProfiles mapping={mapping} delimiter={delimiter} apply={(next,separator)=>{changeMapping(next);setDelimiter(separator);}} preferences={preferences}/>
 {!!source&&<><div className="review-grid">{(['name','date','amount','notes','sourceId'] as const).map(key=><label key={key}>{t(({name:'Name',date:'Date',amount:'Amount',notes:'Notes',sourceId:'Source transaction ID'})[key])}<NativeSelect disabled={busy} value={mapping[key]} onChange={event=>changeMapping({...mapping,[key]:Number(event.target.value)})}>{(key==='notes'||key==='sourceId')&&<option value={-1}>{t('None')}</option>}{headers.map((header,index)=><option value={index} key={index}>{header}</option>)}</NativeSelect></label>)}<label>{t('Date format')}<NativeSelect disabled={busy} value={mapping.dateFormat} onChange={event=>changeMapping({...mapping,dateFormat:event.target.value as ColumnMapping['dateFormat']})}><option value="iso">YYYY-MM-DD</option><option value="dmy">DD/MM/YYYY</option><option value="mdy">MM/DD/YYYY</option></NativeSelect></label><label>{t('Decimal separator')}<NativeSelect disabled={busy} value={mapping.decimal} onChange={event=>changeMapping({...mapping,decimal:event.target.value as '.'|','})}><option value=".">.</option><option value=",">,</option></NativeSelect></label></div><p className="muted">{t('Map a stable source transaction ID when available. Without IDs, overlapping statements with identical purchases can be ambiguous; review duplicates before importing.')}</p><p>{t('Positive amounts are income; negative amounts are expenses. All rows use the selected account currency.')}</p>
 {parseError?<ErrorPopup message={parseError}/>:<><p>{t('{count} selected transactions',{count:formatNumber(rows.length-excluded.length,locale,0)})}</p><div className="table-scroll import-preview"><table><thead><tr><th>{t('Import')}</th><th>{t('Name')}</th><th>{t('Date')}</th><th>{t('Amount')}</th><th>{t('Category')}</th></tr></thead><tbody>{rows.map((row,index)=><tr key={index}><td><Checkbox disabled={busy} checked={!excluded.includes(index)} aria-label={t('Import {name}',{name:row.name})} onCheckedChange={checked=>{setExcluded(checked?excluded.filter(value=>value!==index):[...excluded,index]);setBatchId(null);}}/></td><td>{row.name}</td><td>{formatDate(row.date,locale)}</td><td>{account?formatMoney(row.amount,account.currency,locale):formatNumber(row.amount,locale,0)}</td><td>{t(row.amount>0?'Other income':'Other expense')}</td></tr>)}</tbody></table></div><Button disabled={busy||demo||!account||rows.length===excluded.length} onClick={async()=>{const newBatchId=crypto.randomUUID();if(!batchId)setBatchId(newBatchId);setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({batch_id:batchId??newBatchId,account_id:accountId,rows:rows.map((row,index)=>({...row,selected:!excluded.includes(index)}))})});const result=await response.json() as {error?:string;added:number;skipped:number};if(!response.ok)throw Error(result.error);setMessage(t('Imported {added}; skipped {skipped}.',{added:formatNumber(result.added,locale,0),skipped:formatNumber(result.skipped,locale,0)}));setSource(null);setBatchId(null);showSaved();onSaved();}catch(reason){setError((reason as Error).message);}finally{setBusy(false);}}}>{t(busy?'Importing…':'Import selected transactions')}</Button></>}</>}
 <ErrorPopup message={error}/>{message&&<p role="status">{message}</p>}
 </section>{confirmation}</section>;
}
