"use client";
import {useState} from 'react';
import {useLanguage} from '@/components/language-provider';
import {Button} from '@/components/ui/button';
import {useOwnerResource} from '@/hooks/use-owner-resource';
import {formatDateTime,formatNumber} from '@/lib/format';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
const empty={batches:[] as {id:string;account_id:string;created_at:string;undone_at:string|null;result:{added:number;skipped:number}}[]};
export function ImportHistory({owner,demo,revision,onSaved}:{owner:string|null;demo:boolean;revision:number;onSaved:()=>void}){
 const {t,locale}=useLanguage();const history=useOwnerResource('/api/import',owner,!demo,revision,empty);const [undo,setUndo]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <section className="panel tools-panel"><h2>{t('Statement import history')}</h2>{history.data.batches.length>0&&<p className="muted">{t('Undo removes only unchanged records added by that import and reverses their cash effects. Skipped duplicates remain. Later edits or goal links require individual review.')}</p>}{history.error?<p role="alert">{t(history.error)} <Button onClick={history.retry}>{t('Retry')}</Button></p>:history.loading?<p>{t('Loading records…')}</p>:!history.data.batches.length?<div className="import-history-empty"><strong>{t('No imports yet')}</strong><p className="muted">{t('Imported statements will appear here so you can review or undo them.')}</p></div>:<ul className="tool-list">{history.data.batches.map(batch=><li key={batch.id}><div><strong>{formatDateTime(batch.created_at,locale)}</strong><p>{t('Imported {added}; skipped {skipped}.',{added:formatNumber(batch.result.added,locale,0),skipped:formatNumber(batch.result.skipped,locale,0)})}</p></div>{batch.undone_at?<span>{t('Undone')}</span>:<Button type="button" disabled={busy||batch.result.added===0} variant="outline" onClick={()=>{setError('');setUndo(batch.id);}}>{t('Undo import')}</Button>}</li>)}</ul>}{error&&<p role="alert">{t(error)}</p>}
 <AlertDialog open={!!undo} onOpenChange={open=>{if(!open&&!busy)setUndo(null);}}><AlertDialogContent><AlertDialogTitle>{t('Undo this import?')}</AlertDialogTitle><AlertDialogDescription>{t('All unchanged transactions added by this import will be removed together. This also changes the cash account balance.')}</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={busy}>{t('Cancel')}</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async event=>{event.preventDefault();setBusy(true);setError('');try{const response=await fetch('/api/import',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:undo})});const result=await response.json() as {error?:string};if(!response.ok)throw Error(result.error);setUndo(null);history.invalidate();onSaved();}catch(e){setError((e as Error).message);setUndo(null);}finally{setBusy(false);}}}>{t(busy?'Saving…':'Undo import')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>;
}
