"use client";
import { DiversifiedPortfolioSettings } from '@/components/diversified-portfolio-settings';
import { defaultDiversifiedPortfolio, diversifiedPortfolioSchema } from '@/lib/diversified-portfolio';
import { useEffect,useState } from 'react';
import { useLanguage } from '@/components/language-provider';
import { Button } from '@/components/ui/button';
import { InstrumentPicker } from '@/components/instrument-picker';
import { instrumentFor } from '@/lib/market';
import { LoadingPlaceholder } from '@/components/loading-placeholder';
import { defaultComparisonPreferences,type BenchmarkKey,type ComparisonPreferences,type ComparisonProfile } from '@/lib/comparison-profile';
import { formatNumber } from '@/lib/format';
export function InvestmentComparisonSettings({demo}:{demo:boolean}){
 const {t,locale}=useLanguage();
 const [draft,setDraft]=useState<ComparisonPreferences>(defaultComparisonPreferences);
 const [loading,setLoading]=useState(!demo),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{if(demo)return;const controller=new AbortController();fetch('/api/comparison-profile',{signal:controller.signal}).then(async response=>{const data=await response.json() as ComparisonProfile&{error?:string};if(!response.ok)throw Error(data.error);if(!controller.signal.aborted){setDraft(data.preferences);setError('');setLoading(false);}}).catch(reason=>{if(!controller.signal.aborted){setError(reason.message);setLoading(false);}});return()=>controller.abort();},[demo,retry]);
 const options:Array<{key:BenchmarkKey;label:string}>=[{key:'BTC',label:'Bitcoin · BTC'},{key:'SPY',label:'S&P 500 · SPY'},{key:'HYG',label:t('High-yield bonds · HYG')},{key:'depositUZS',label:t('{currency} deposit · {rate}%',{currency:'UZS',rate:formatNumber(21,locale)})},{key:'depositUSD',label:t('{currency} deposit · {rate}%',{currency:'USD',rate:formatNumber(8,locale)})},{key:'CUSTOM',label:t('Another USD stock or ETF')},{key:'PORTFOLIO',label:t('Diversified portfolio')}];
 async function save(){if(draft.benchmarks.includes('PORTFOLIO')&&!diversifiedPortfolioSchema.safeParse(draft.portfolio).success)return;setBusy(true);setMessage('');try{const response=await fetch('/api/comparison-profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,portfolio:diversifiedPortfolioSchema.safeParse(draft.portfolio).success?draft.portfolio:null})});if(!response.ok){const data=await response.json() as {error:string};throw Error(data.error);}setMessage('Comparison choices saved.');}catch(reason){setMessage((reason as Error).message);}finally{setBusy(false);}}
 return <section className="panel settings-form comparison-settings"><h2>{t('Investment benchmarks')}</h2><p className="muted">{t('Record your real investments in Assets & investments. Choose what to compare them against here.')}</p><p className="muted">{t('For example: your livestock or café versus buying Bitcoin with the same amounts on the same dates.')}</p>{loading?<LoadingPlaceholder label={t('Loading settings…')}/>:error?<p className="error" role="alert">{t(error)} <Button variant="outline" onClick={()=>{setLoading(true);setRetry(n=>n+1);}}>{t('Retry')}</Button></p>:<form onSubmit={event=>{event.preventDefault();void save();}}><div className="comparison-settings-options">{options.map(option=><label key={option.key}><input type="checkbox" checked={draft.benchmarks.includes(option.key)} disabled={draft.benchmarks.length===1&&draft.benchmarks.includes(option.key)} onChange={event=>setDraft({...draft,portfolio:option.key==='PORTFOLIO'&&event.target.checked?(draft.portfolio??defaultDiversifiedPortfolio):draft.portfolio,benchmarks:event.target.checked?[...draft.benchmarks,option.key]:draft.benchmarks.filter(key=>key!==option.key)})}/>{option.label}</label>)}</div>{draft.benchmarks.includes('CUSTOM')&&<InstrumentPicker kind="Stock" value={draft.custom_symbol} disabled={busy} onChange={value=>{const symbol=instrumentFor({kind:'Stock',name:value})?.symbol??'';setDraft({...draft,custom_symbol:symbol});setMessage('');}}/>}{draft.benchmarks.includes('PORTFOLIO')&&<DiversifiedPortfolioSettings value={draft.portfolio??defaultDiversifiedPortfolio} onChange={portfolio=>{setDraft({...draft,portfolio});setMessage('');}}/>}<p className="comparison-note">{t('Changing benchmarks does not reset your investment history or your app start date.')}</p>{message&&<p role="status">{t(message)}</p>}<Button disabled={busy||demo||(draft.benchmarks.includes('PORTFOLIO')&&!diversifiedPortfolioSchema.safeParse(draft.portfolio).success)||(draft.benchmarks.includes('CUSTOM')&&!draft.custom_symbol)} type="submit">{t(busy?'Saving…':'Save comparison choices')}</Button>{demo&&<p className="comparison-note">{t('Sign in to save investment comparisons.')}</p>}</form>}</section>;
}
