import { coins, coinName } from './market';

// Suggestions are available offline. Unlisted USD stock tickers can still be entered.
export const stocks = [
 ['AAPL','Apple'], ['MSFT','Microsoft'], ['NVDA','NVIDIA'], ['AMZN','Amazon'],
 ['GOOGL','Alphabet (Class A)'], ['GOOG','Alphabet (Class C)'], ['META','Meta Platforms'], ['TSLA','Tesla'],
 ['BRK.B','Berkshire Hathaway (Class B)'], ['AVGO','Broadcom'], ['TSM','Taiwan Semiconductor (ADR)'], ['AMD','Advanced Micro Devices'],
 ['INTC','Intel'], ['QCOM','Qualcomm'], ['MU','Micron Technology'], ['ARM','Arm Holdings (ADR)'],
 ['ORCL','Oracle'], ['CRM','Salesforce'], ['ADBE','Adobe'], ['NOW','ServiceNow'],
 ['PLTR','Palantir Technologies'], ['NFLX','Netflix'], ['UBER','Uber Technologies'], ['SHOP','Shopify'],
 ['JPM','JPMorgan Chase'], ['BAC','Bank of America'], ['GS','Goldman Sachs'], ['MS','Morgan Stanley'],
 ['V','Visa'], ['MA','Mastercard'], ['AXP','American Express'], ['PYPL','PayPal'],
 ['WMT','Walmart'], ['COST','Costco Wholesale'], ['HD','Home Depot'], ['MCD',"McDonald's"],
 ['KO','Coca-Cola'], ['PEP','PepsiCo'], ['PG','Procter & Gamble'], ['NKE','Nike'],
 ['DIS','Walt Disney'], ['SBUX','Starbucks'], ['JNJ','Johnson & Johnson'], ['PFE','Pfizer'],
 ['LLY','Eli Lilly'], ['ABBV','AbbVie'], ['UNH','UnitedHealth Group'], ['MRK','Merck'],
 ['XOM','Exxon Mobil'], ['CVX','Chevron'], ['CAT','Caterpillar'], ['GE','GE Aerospace'],
 ['BA','Boeing'], ['LMT','Lockheed Martin'], ['COIN','Coinbase'], ['MSTR','Strategy'],
 ['BABA','Alibaba (ADR)'], ['BIDU','Baidu (ADR)'], ['NIO','NIO (ADR)'], ['SONY','Sony Group (ADR)'],
 ['SPY','SPDR S&P 500 ETF'], ['VOO','Vanguard S&P 500 ETF'], ['VTI','Vanguard Total Stock Market ETF'], ['QQQ','Invesco QQQ ETF'],
 ['SCHD','Schwab U.S. Dividend Equity ETF'], ['DIA','SPDR Dow Jones Industrial Average ETF'], ['IWM','iShares Russell 2000 ETF'], ['GLD','SPDR Gold Shares ETF'],
 ['IBM','IBM'], ['CSCO','Cisco Systems'], ['TXN','Texas Instruments'], ['AMAT','Applied Materials'],
 ['LRCX','Lam Research'], ['KLAC','KLA'], ['ASML','ASML Holding'], ['ADI','Analog Devices'],
 ['MRVL','Marvell Technology'], ['SNPS','Synopsys'], ['CDNS','Cadence Design Systems'], ['ANET','Arista Networks'],
 ['DELL','Dell Technologies'], ['HPQ','HP'], ['HPE','Hewlett Packard Enterprise'], ['SMCI','Super Micro Computer'],
 ['PANW','Palo Alto Networks'], ['CRWD','CrowdStrike'], ['FTNT','Fortinet'], ['ZS','Zscaler'],
 ['NET','Cloudflare'], ['OKTA','Okta'], ['DDOG','Datadog'], ['SNOW','Snowflake'],
 ['MDB','MongoDB'], ['TEAM','Atlassian'], ['WDAY','Workday'], ['INTU','Intuit'],
 ['ADP','Automatic Data Processing'], ['ACN','Accenture'], ['SAP','SAP (ADR)'], ['HUBS','HubSpot'],
 ['TWLO','Twilio'], ['ZM','Zoom Communications'], ['U','Unity Software'], ['PATH','UiPath'],
 ['APP','AppLovin'], ['AI','C3.ai'], ['SOUN','SoundHound AI'], ['CRWV','CoreWeave'],
 ['NBIS','Nebius Group'], ['IONQ','IonQ'], ['RGTI','Rigetti Computing'], ['QBTS','D-Wave Quantum'],
 ['RKLB','Rocket Lab'], ['ASTS','AST SpaceMobile'], ['RDDT','Reddit'], ['SPOT','Spotify'],
 ['PINS','Pinterest'], ['SNAP','Snap'], ['RBLX','Roblox'], ['TTWO','Take-Two Interactive'],
 ['ROKU','Roku'], ['ABNB','Airbnb'], ['BKNG','Booking Holdings'], ['DASH','DoorDash'],
 ['LYFT','Lyft'], ['EBAY','eBay'], ['CVNA','Carvana'], ['DKNG','DraftKings'],
 ['MELI','MercadoLibre'], ['SE','Sea Limited (ADR)'], ['GRAB','Grab Holdings'], ['CPNG','Coupang'],
 ['PDD','PDD Holdings (ADR)'], ['JD','JD.com (ADR)'], ['NTES','NetEase (ADR)'], ['LI','Li Auto (ADR)'],
 ['XPEV','XPeng (ADR)'], ['WFC','Wells Fargo'], ['C','Citigroup'], ['SCHW','Charles Schwab'],
 ['BLK','BlackRock'], ['BX','Blackstone'], ['KKR','KKR'], ['APO','Apollo Global Management'],
 ['COF','Capital One'], ['USB','U.S. Bancorp'], ['PNC','PNC Financial Services'], ['TFC','Truist Financial'],
 ['SPGI','S&P Global'], ['MCO',"Moody's"], ['ICE','Intercontinental Exchange'], ['CME','CME Group'],
 ['CB','Chubb'], ['PGR','Progressive'], ['AIG','American International Group'], ['MET','MetLife'],
 ['PRU','Prudential Financial'], ['FIS','Fidelity National Information Services'], ['FISV','Fiserv'], ['GPN','Global Payments'],
 ['HOOD','Robinhood Markets'], ['SOFI','SoFi Technologies'], ['AFRM','Affirm'], ['XYZ','Block'],
 ['UPST','Upstart'], ['NU','Nu Holdings'], ['CRCL','Circle Internet Group'], ['GLXY','Galaxy Digital'],
 ['MARA','MARA Holdings'], ['RIOT','Riot Platforms'], ['CLSK','CleanSpark'], ['IREN','IREN'],
 ['HUT','Hut 8'], ['BMNR','BitMine Immersion Technologies'], ['TD','Toronto-Dominion Bank'], ['RY','Royal Bank of Canada'],
 ['HSBC','HSBC Holdings (ADR)'], ['UBS','UBS Group'], ['SAN','Banco Santander (ADR)'], ['ING','ING Group (ADR)'],
 ['MUFG','Mitsubishi UFJ Financial (ADR)'], ['HDB','HDFC Bank (ADR)'], ['IBN','ICICI Bank (ADR)'], ['INFY','Infosys (ADR)'],
 ['TGT','Target'], ['LOW',"Lowe's"], ['TJX','TJX Companies'], ['ROST','Ross Stores'],
 ['LULU','Lululemon Athletica'], ['DG','Dollar General'], ['DLTR','Dollar Tree'], ['BBY','Best Buy'],
 ['KR','Kroger'], ['CVS','CVS Health'], ['CMG','Chipotle Mexican Grill'], ['YUM','Yum! Brands'],
 ['DPZ',"Domino's Pizza"], ['DRI','Darden Restaurants'], ['MAR','Marriott International'], ['HLT','Hilton Worldwide'],
 ['RCL','Royal Caribbean'], ['CCL','Carnival'], ['NCLH','Norwegian Cruise Line'], ['DAL','Delta Air Lines'],
 ['UAL','United Airlines'], ['AAL','American Airlines'], ['LUV','Southwest Airlines'], ['F','Ford Motor'],
 ['GM','General Motors'], ['RIVN','Rivian Automotive'], ['LCID','Lucid Group'], ['STLA','Stellantis'],
 ['RACE','Ferrari'], ['TM','Toyota Motor (ADR)'], ['HMC','Honda Motor (ADR)'], ['PM','Philip Morris International'],
 ['MO','Altria'], ['MDLZ','Mondelez International'], ['KHC','Kraft Heinz'], ['GIS','General Mills'],
 ['CL','Colgate-Palmolive'], ['KMB','Kimberly-Clark'], ['EL','Estée Lauder'], ['MNST','Monster Beverage'],
 ['CELH','Celsius Holdings'], ['KDP','Keurig Dr Pepper'], ['STZ','Constellation Brands'], ['BUD','Anheuser-Busch InBev (ADR)'],
 ['UL','Unilever (ADR)'], ['DEO','Diageo (ADR)'], ['TMO','Thermo Fisher Scientific'], ['ABT','Abbott Laboratories'],
 ['DHR','Danaher'], ['AMGN','Amgen'], ['GILD','Gilead Sciences'], ['BMY','Bristol-Myers Squibb'],
 ['VRTX','Vertex Pharmaceuticals'], ['REGN','Regeneron Pharmaceuticals'], ['ISRG','Intuitive Surgical'], ['MDT','Medtronic'],
 ['SYK','Stryker'], ['BSX','Boston Scientific'], ['ELV','Elevance Health'], ['CI','Cigna'],
 ['HUM','Humana'], ['HCA','HCA Healthcare'], ['ZTS','Zoetis'], ['MRNA','Moderna'],
 ['BNTX','BioNTech (ADR)'], ['HIMS','Hims & Hers Health'], ['NVO','Novo Nordisk (ADR)'], ['AZN','AstraZeneca (ADR)'],
 ['NVS','Novartis (ADR)'], ['GSK','GSK (ADR)'], ['SNY','Sanofi (ADR)'], ['HON','Honeywell'],
 ['UNP','Union Pacific'], ['UPS','United Parcel Service'], ['FDX','FedEx'], ['RTX','RTX'],
 ['NOC','Northrop Grumman'], ['GD','General Dynamics'], ['DE','Deere & Company'], ['MMM','3M'],
 ['EMR','Emerson Electric'], ['ETN','Eaton'], ['GEV','GE Vernova'], ['GEHC','GE HealthCare'],
 ['WM','Waste Management'], ['LIN','Linde'], ['SHW','Sherwin-Williams'], ['FCX','Freeport-McMoRan'],
 ['NEM','Newmont'], ['AA','Alcoa'], ['NUE','Nucor'], ['RIO','Rio Tinto (ADR)'],
 ['BHP','BHP Group (ADR)'], ['VALE','Vale (ADR)'], ['COP','ConocoPhillips'], ['SLB','SLB'],
 ['EOG','EOG Resources'], ['OXY','Occidental Petroleum'], ['MPC','Marathon Petroleum'], ['PSX','Phillips 66'],
 ['KMI','Kinder Morgan'], ['BP','BP (ADR)'], ['SHEL','Shell (ADR)'], ['TTE','TotalEnergies (ADR)'],
 ['PBR','Petrobras (ADR)'], ['NEE','NextEra Energy'], ['DUK','Duke Energy'], ['SO','Southern Company'],
 ['CEG','Constellation Energy'], ['VST','Vistra'], ['FSLR','First Solar'], ['ENPH','Enphase Energy'],
 ['T','AT&T'], ['VZ','Verizon'], ['TMUS','T-Mobile US'], ['CMCSA','Comcast'],
 ['CHTR','Charter Communications'], ['AMT','American Tower'], ['PLD','Prologis'], ['EQIX','Equinix'],
 ['O','Realty Income'], ['SPG','Simon Property Group'], ['DLR','Digital Realty'], ['PSA','Public Storage'],
 ['IVV','iShares Core S&P 500 ETF'], ['SPYM','SPDR Portfolio S&P 500 ETF'], ['RSP','Invesco S&P 500 Equal Weight ETF'], ['QQQM','Invesco NASDAQ 100 ETF'],
 ['VT','Vanguard Total World Stock ETF'], ['VXUS','Vanguard Total International Stock ETF'], ['VEA','Vanguard FTSE Developed Markets ETF'], ['VWO','Vanguard FTSE Emerging Markets ETF'],
 ['VUG','Vanguard Growth ETF'], ['VTV','Vanguard Value ETF'], ['VIG','Vanguard Dividend Appreciation ETF'], ['VYM','Vanguard High Dividend Yield ETF'],
 ['VB','Vanguard Small-Cap ETF'], ['VO','Vanguard Mid-Cap ETF'], ['VGT','Vanguard Information Technology ETF'], ['VNQ','Vanguard Real Estate ETF'],
 ['VGK','Vanguard FTSE Europe ETF'], ['SCHG','Schwab U.S. Large-Cap Growth ETF'], ['SCHB','Schwab U.S. Broad Market ETF'], ['SCHX','Schwab U.S. Large-Cap ETF'],
 ['IJH','iShares Core S&P Mid-Cap ETF'], ['IJR','iShares Core S&P Small-Cap ETF'], ['AVUV','Avantis U.S. Small Cap Value ETF'], ['EFA','iShares MSCI EAFE ETF'],
 ['IEFA','iShares Core MSCI EAFE ETF'], ['EEM','iShares MSCI Emerging Markets ETF'], ['IEMG','iShares Core MSCI Emerging Markets ETF'], ['EWJ','iShares MSCI Japan ETF'],
 ['INDA','iShares MSCI India ETF'], ['EWZ','iShares MSCI Brazil ETF'], ['FXI','iShares China Large-Cap ETF'], ['MCHI','iShares MSCI China ETF'],
 ['KWEB','KraneShares CSI China Internet ETF'], ['XLK','Technology Select Sector SPDR ETF'], ['XLF','Financial Select Sector SPDR ETF'], ['XLE','Energy Select Sector SPDR ETF'],
 ['XLV','Health Care Select Sector SPDR ETF'], ['XLY','Consumer Discretionary Select Sector SPDR ETF'], ['XLP','Consumer Staples Select Sector SPDR ETF'], ['XLI','Industrial Select Sector SPDR ETF'],
 ['XLU','Utilities Select Sector SPDR ETF'], ['SMH','VanEck Semiconductor ETF'], ['SOXX','iShares Semiconductor ETF'], ['ARKK','ARK Innovation ETF'],
 ['MTUM','iShares MSCI USA Momentum Factor ETF'], ['QUAL','iShares MSCI USA Quality Factor ETF'], ['USMV','iShares MSCI USA Min Vol Factor ETF'], ['COWZ','Pacer US Cash Cows 100 ETF'],
 ['DGRO','iShares Core Dividend Growth ETF'], ['DVY','iShares Select Dividend ETF'], ['NOBL','ProShares S&P 500 Dividend Aristocrats ETF'], ['JEPI','JPMorgan Equity Premium Income ETF'],
 ['JEPQ','JPMorgan Nasdaq Equity Premium Income ETF'], ['TQQQ','ProShares UltraPro QQQ'], ['SQQQ','ProShares UltraPro Short QQQ'], ['SOXL','Direxion Daily Semiconductor Bull 3X ETF'],
 ['BND','Vanguard Total Bond Market ETF'], ['BNDX','Vanguard Total International Bond ETF'], ['AGG','iShares Core U.S. Aggregate Bond ETF'], ['TLT','iShares 20+ Year Treasury Bond ETF'],
 ['IEF','iShares 7-10 Year Treasury Bond ETF'], ['SHY','iShares 1-3 Year Treasury Bond ETF'], ['SGOV','iShares 0-3 Month Treasury Bond ETF'], ['BIL','SPDR Bloomberg 1-3 Month T-Bill ETF'],
 ['HYG','iShares iBoxx High Yield Corporate Bond ETF'], ['LQD','iShares iBoxx Investment Grade Corporate Bond ETF'], ['TIP','iShares TIPS Bond ETF'], ['MUB','iShares National Muni Bond ETF'],
 ['IAU','iShares Gold Trust'], ['SLV','iShares Silver Trust'], ['USO','United States Oil Fund'], ['IBIT','iShares Bitcoin Trust ETF'],
 ['FBTC','Fidelity Wise Origin Bitcoin Fund'], ['GBTC','Grayscale Bitcoin Trust'], ['BITO','ProShares Bitcoin ETF'], ['ETHA','iShares Ethereum Trust ETF'],
] as const;
export type InstrumentOption = { symbol:string; name:string; value:string };
export function instrumentOptions(kind:'Crypto'|'Stock'):InstrumentOption[] {
 return (kind==='Crypto'?coins:stocks).map(item=>({symbol:item[0],name:item[1],value:kind==='Crypto'?coinName(item):item[0]}));
}
export function matchingInstruments(kind:'Crypto'|'Stock',query:string) {
 const terms=query.trim().toLowerCase().split(/\s+/).filter(Boolean);
 const normalized=query.trim().toUpperCase();
 return instrumentOptions(kind).filter(item=>terms.every(term=>(item.symbol+' '+item.name).toLowerCase().includes(term)))
  .sort((a,b)=>Number(b.symbol===normalized)-Number(a.symbol===normalized));
}
export function customStockSymbol(query:string) {
 const symbol=query.trim().toUpperCase();
 return /^[A-Z][A-Z0-9.-]{0,14}$/.test(symbol)&&!stocks.some(item=>item[0]===symbol)?symbol:null;
}
