import { cookies } from 'next/headers';
import { tokenVerifier } from './supabase-jwt';
type AuthSession = {access_token:string;refresh_token:string;expires_in:number;user:{id:string;email:string;phone?:string}};
export function config(){const url=process.env.SUPABASE_URL;const key=process.env.SUPABASE_PUBLISHABLE_KEY;if(!url||!key)throw new Error('Supabase connection is not configured yet.');return {url,key};}
export async function supa(path:string,init:RequestInit={},token?:string){const {url,key}=config();return fetch(url+path,{cache:'no-store',signal:AbortSignal.timeout(15000),...init,headers:{apikey:key,'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`} :{}),...init.headers}});}
export async function saveSession(s:{access_token:string;refresh_token:string;expires_in:number}){const c=await cookies();const options={httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax' as const,path:'/'};c.set('hf_access',s.access_token,{...options,maxAge:s.expires_in});c.set('hf_refresh',s.refresh_token,{...options,maxAge:60*60*24*30});}
// Access tokens are checked locally against Supabase's published keys; Supabase Auth is asked only when that fails.
let verifier:ReturnType<typeof tokenVerifier>|null=null;
function verifyLocally(token:string){const {url,key}=config();verifier??=tokenVerifier(url+'/auth/v1',{now:Date.now,fetchKeys:async()=>{const r=await fetch(url+'/auth/v1/.well-known/jwks.json',{headers:{apikey:key},signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error('Signing keys are unavailable.');return ((await r.json()) as {keys?:JsonWebKey[]}).keys??[];}});return verifier(token);}
export async function session(){const c=await cookies();const token=c.get('hf_access')?.value;if(token){const local=await verifyLocally(token);if(local)return {token,user:local};const r=await supa('/auth/v1/user',{},token);if(r.ok)return {token,user:await r.json() as AuthSession["user"]};}const refresh=c.get('hf_refresh')?.value;if(refresh){const r=await supa('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:refresh})});if(r.ok){const s=await r.json() as AuthSession;await saveSession(s);return {token:s.access_token,user:s.user};}}return null;}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');return !origin||origin===new URL(req.url).origin;}
