import { isCurrency } from '@/lib/currencies';
import { z } from 'zod';
import { kinds } from '@/lib/finance';
import { session,supa,sameOrigin } from '@/lib/supabase';
const validDate=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!Number.isNaN(Date.parse(v)) && new Date(v).toISOString().slice(0,10)===v);
const schema=z.object({id:z.string().uuid(),name:z.string().trim().min(1).max(120),kind:z.enum(kinds),currency:z.string().refine(isCurrency),amount:z.number().finite().min(0).max(1e15),quantity:z.number().finite().min(0).max(1e12),cost:z.number().finite().min(0).max(1e15),rate:z.number().finite().min(0).max(1000),date:z.union([validDate,z.literal('')]),lent_date:z.union([validDate,z.literal('')]).optional(),frequency:z.enum(['Once','Monthly','Yearly']),notes:z.string().max(2000)}).superRefine((r,ctx)=>{if(r.kind==='Money lent'){if(!r.lent_date)ctx.addIssue({code:'custom',path:['lent_date'],message:'Date lent is required.'});if(r.date && r.lent_date && r.date<r.lent_date)ctx.addIssue({code:'custom',path:['date'],message:'Due date must not precede lending date.'});}else if(!r.date)ctx.addIssue({code:'custom',path:['date'],message:'Date is required.'});});
async function handle(req:Request,method:string){if(method!=='GET'&&!sameOrigin(req))return new Response(null,{status:403});try{const s=await session();if(!s)return Response.json({error:'Please sign in again.'},{status:401});let path='/rest/v1/finance_records';let init:RequestInit={};if(method==='GET'){
 const params=new URL(req.url).searchParams;
 const query=z.object({page:z.coerce.number().int().min(1).max(1000000),section:z.enum(['all','assets','cashflow','debts']),currency:z.string().refine(isCurrency).nullable(),summary:z.enum(['0','1'])}).safeParse({page:params.get('page')||'1',section:params.get('section')||'all',currency:params.get('currency'),summary:params.get('summary')||'0'});
 if(!query.success)return Response.json({error:'Invalid pagination parameters.'},{status:400});
 path='/rest/v1/rpc/finance_records_page';init={method:'POST',body:JSON.stringify({p_page:query.data.page,p_section:query.data.section,p_currency:query.data.currency,p_summary:query.data.summary==='1'})};
 }else if(method==='DELETE'){const {id}=await req.json() as {id:unknown};if(!z.string().uuid().safeParse(id).success)return new Response(null,{status:400});path+='?id=eq.'+id;init={method:'DELETE'};}else{const parsed=schema.safeParse(await req.json());if(!parsed.success)return Response.json({error:'Check the record fields.'},{status:400});init={method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({...parsed.data,date:parsed.data.date || null,lent_date:parsed.data.kind==='Money lent'?parsed.data.lent_date:null,user_id:s.user.id})};path+='?on_conflict=id';}const r=await supa(path,init,s.token);if(!r.ok)return Response.json({error:'Could not access your records. Confirm the database setup and try again.'},{status:503});return Response.json(method==='DELETE'?{ok:true}:await r.json());}catch{return Response.json({error:'Connection unavailable. Your changes have not been saved.'},{status:503});}}
export const GET=(r:Request)=>handle(r,'GET');export const POST=(r:Request)=>handle(r,'POST');export const DELETE=(r:Request)=>handle(r,'DELETE');
