"use client";
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { NativeSelect } from '@/components/ui/native-select';
import { CategoryBadge } from '@/components/category-badge';
import { useLanguage } from '@/components/language-provider';
import { formatDate,formatMoney,formatNumber } from '@/lib/format';
import { income } from '@/lib/finance';
import { parseCSV,mapCSV,type ColumnMapping,type ImportRow } from '@/lib/csv';
import type { PlanningData } from '@/lib/planning';
export function DataTools({data,demo,save,onSaved}:{data:PlanningData;demo:boolean;save:(action:string,data:unknown)=>Promise<void>;onSaved:()=>void}){
 const {t,locale}=useLanguage();const [name,setName]=useState(''),[categoryId,setCategoryId]=useState('');const [account,setAccount]=useState(''),[source,setSource]=useState(''),[delimiter,setDelimiter]=useState(',');
 const [mapping,setMapping]=useState<ColumnMapping>({name:0,date:1,amount:2,notes:-1,dateFormat:'iso',decimal:'.'});
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[preview,setPreview]=useState<Array<ImportRow & {selected?:boolean}>|null>(null);
 let rows:string[][]=[],parseError='';try{if(source)rows=parseCSV(source,delimiter);}catch(e){parseError=(e as Error).message;}
 const accounts=data.records.filter(r=>r.kind==='Cash'),selected=accounts.find(a=>a.id===account);
 async function download(format:string){setBusy(true);setError('');try{const r=await fetch('/api/backup'+(format==='csv'?'?format=csv':''));if(!r.ok)throw Error((await r.json() as {error:string}).error);const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=format==='csv'?'finance-records.csv':'finance-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><div className="page-heading"><div><h1>{t('Data & categories')}</h1><p className="muted">{t('Bring in statements, keep a backup and organize your spending.')}</p></div></div>
 {error&&<p className="error" role="alert">{t(error)}</p>}{message&&<p role="status">{message}</p>}
 <section className="panel"><h2>{t('Export & backup')}</h2><p className="muted">{t('CSV contains your records. The complete backup includes histories, budgets, goals and settings.')}</p><div className="row-actions"><Button disabled={busy||demo} onClick={()=>download('csv')}>{t('Export CSV')}</Button><Button variant="outline" disabled={busy||demo} onClick={()=>download('json')}>{t('Download complete backup')}</Button></div></section>
 <section className="panel"><h2>{t('Custom categories')}</h2><div className="row-actions">{data.categories.map(c=><Button variant="ghost" key={c.id} onClick={()=>{setCategoryId(c.id);setName(c.name);}}><CategoryBadge kind={c.id} label={c.name}/></Button>)}</div><form className="planning-inline" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await save('category',{id:categoryId||crypto.randomUUID(),name});setName('');setCategoryId('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Input aria-label={t('Category name')} placeholder={t('Category name')} required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/><Button disabled={busy||demo}>{t(categoryId?'Save':'Add category')}</Button>{categoryId&&<Button type="button" variant="outline" onClick={()=>{setCategoryId('');setName('');}}>{t('Cancel')}</Button>}</form></section>
 <section className="panel"><h2>{t('Import bank CSV')}</h2><p className="muted">{t('Use signed amounts: positive for income, negative for spending. Start with the account balance before these transactions. Importing changes its balance.')}</p><p className="muted">{t('Repeated imports match account, date, description and amount. Review overlapping files carefully. Transfers should be recorded separately, not imported as income and expenses.')}</p>
 <div className="record-form"><label>{t('Cash account')}<NativeSelect value={account} onChange={e=>{setAccount(e.target.value);setPreview(null);}}><option value="">{t('Select account')}</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.currency}</option>)}</NativeSelect></label>
 <label>{t('CSV file')}<Input type="file" accept=".csv,text/csv" disabled={busy} onChange={async e=>{setPreview(null);setMessage('');const f=e.target.files?.[0];if(!f)return;if(f.size>2_000_000){setError('File is too large.');return;}setSource(await f.text());}}/></label>
 <label>{t('Delimiter')}<NativeSelect value={delimiter} onChange={e=>{setDelimiter(e.target.value);setPreview(null);}}><option value=",">{t('Comma')}</option><option value=";">{t('Semicolon')}</option><option value={'\t'}>{t('Tab')}</option></NativeSelect></label>
 {parseError&&<p className="error">{t(parseError)}</p>}
 {rows.length>0&&<><div className="form-grid">{(['name','date','amount','notes'] as const).map(key=><label key={key}>{t(({name:'Name',date:'Date',amount:'Amount',notes:'Notes (optional)'})[key])}<NativeSelect value={mapping[key]} onChange={e=>{setMapping({...mapping,[key]:Number(e.target.value)});setPreview(null);}}>{key==='notes'&&<option value={-1}>{t('None')}</option>}{rows[0].map((header,i)=><option key={i} value={i}>{header}</option>)}</NativeSelect></label>)}</div><div className="form-grid"><label>{t('Date format')}<NativeSelect value={mapping.dateFormat} onChange={e=>{setMapping({...mapping,dateFormat:e.target.value as ColumnMapping['dateFormat']});setPreview(null);}}><option value="iso">YYYY-MM-DD</option><option value="dmy">DD/MM/YYYY</option><option value="mdy">MM/DD/YYYY</option></NativeSelect></label><label>{t('Decimal separator')}<NativeSelect value={mapping.decimal} onChange={e=>{setMapping({...mapping,decimal:e.target.value as '.'|','});setPreview(null);}}><option value=".">.</option><option value=",">,</option></NativeSelect></label></div><Button variant="outline" disabled={!account||busy} onClick={()=>{try{setPreview(mapCSV(rows,mapping));setError('');}catch(e){setError((e as Error).message);}}}>{t('Preview import')}</Button></>}
 {preview&&<><p>{t('Transactions')}: {formatNumber(preview.filter(r=>r.selected!==false).length,locale,0)}</p><div className="table-scroll import-preview"><table><thead><tr><th>{t('Include')}</th><th>{t('Date')}</th><th>{t('Name')}</th><th>{t('Amount')}</th></tr></thead><tbody>{preview.map((r,i)=><tr key={i}><td><input type="checkbox" aria-label={t('Include {name}',{name:r.name})} checked={r.selected!==false} disabled={busy} onChange={e=>setPreview(preview.map((item,j)=>j===i?{...item,selected:e.target.checked}:item))}/></td><td>{formatDate(r.date,locale)}</td><td>{r.name}{data.records.some(saved=>saved.account_id===account&&saved.name===r.name&&saved.date===r.date&&Number(saved.amount)*(income.includes(saved.kind)?1:-1)===r.amount)&&<small className="block negative">{t('Possible duplicate. Review before importing.')}</small>}</td><td>{formatMoney(r.amount,selected?.currency??'USD',locale)}</td></tr>)}</tbody></table></div><Button disabled={busy||demo||!preview.some(r=>r.selected!==false)} onClick={async()=>{setBusy(true);setError('');try{const r=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({account_id:account,rows:preview})});const d=await r.json() as {error?:string;added:number;skipped:number};if(!r.ok)throw Error(d.error);setMessage(t('Imported {added}; skipped {skipped} duplicates.',{added:formatNumber(d.added,locale,0),skipped:formatNumber(d.skipped,locale,0)}));setPreview(null);setSource('');onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{t(busy?'Importing…':'Import reviewed transactions')}</Button></>}
 </div></section>{demo&&<p className="muted">{t('Sign in to save planning changes.')}</p>}</>;
}
