"use client";
import {useState} from 'react';
import {useLanguage} from '@/components/language-provider';
import {useUnsavedNavigation} from '@/components/discard-changes';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {DatePicker} from '@/components/date-picker';
import {FormattedNumberInput} from '@/components/formatted-number-input';
import {formatMoney,formatDate} from '@/lib/format';
import {projectGoalScenario} from '@/lib/goal-projection';
import type {Goal} from '@/lib/planning';
import type {PreferenceResource} from '@/hooks/use-workspace-preferences';
export function GoalScenarios({goal,starting,currency,today,preferences}:{goal:Goal;starting:number|null;currency:string;today:string;preferences:PreferenceResource}){
 const {t,locale}=useLanguage();const all=preferences.data.preferences.find(p=>p.key==='goal_scenarios')?.data.items??[],scenarios=all.filter(s=>s.goal_id===goal.id);
 const [name,setName]=useState(''),[monthly,setMonthly]=useState(goal.monthly_contribution??0),[rate,setRate]=useState(goal.annual_return??0),[inflation,setInflation]=useState(0),[deadline,setDeadline]=useState(goal.target_date??''),[missed,setMissed]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const guard=useUnsavedNavigation(!!name);
 const money=(value:number)=>formatMoney(value,currency,locale);
 return <section className="panel tools-panel"><h2>{t('Saved goal scenarios')}</h2><p>{t('Compare contribution, return and inflation assumptions independently. Targets keep today’s purchasing power; existing wealth stays constant. These scenarios do not reserve money or change the shared funding plan.')}</p>
 {preferences.loading?<p>{t('Loading records…')}</p>:preferences.error?<p role="alert">{t(preferences.error)} <Button onClick={preferences.retry}>{t('Retry')}</Button></p>:<><div className="review-grid">{scenarios.map(scenario=>{const result=starting===null?null:projectGoalScenario(starting,goal.target,today,scenario);return <article key={scenario.id}><h3>{scenario.name}</h3><p>{formatDate(scenario.deadline,locale)}</p><strong>{t('Projected value')}: {result?money(result.projected):'—'}</strong><p>{t('Value in today’s money')}: {result?money(result.realValue):'—'}</p><p>{t('Inflation-adjusted target')}: {result?money(result.inflatedTarget):'—'}</p><p>{t('Required monthly contribution')}: {result?.required==null?'—':money(Math.ceil(result.required))}</p><Button variant="outline" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await preferences.save({key:'goal_scenarios',data:{items:all.filter(item=>item.id!==scenario.id)}});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{t('Remove')}</Button></article>;})}</div>
 <details><summary>{t('Save a scenario')}</summary><form onSubmit={async event=>{event.preventDefault();setBusy(true);setError('');try{await preferences.save({key:'goal_scenarios',data:{items:[...all,{id:crypto.randomUUID(),goal_id:goal.id,name,monthly,annual_return:rate,inflation,deadline,missed_date:missed||null}]}});setName('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><fieldset className="tracker-fields" disabled={busy||goal.archived}><label>{t('Scenario name')}<Input value={name} maxLength={80} required onChange={event=>setName(event.target.value)}/></label><label>{t('Monthly investment')}<FormattedNumberInput value={monthly} required={false} onValueChange={setMonthly}/></label><label>{t('Annual return assumption')} (%)<FormattedNumberInput value={rate} required={false} max={100} onValueChange={setRate}/></label><label>{t('Annual inflation')} (%)<FormattedNumberInput value={inflation} required={false} max={100} onValueChange={setInflation}/></label><label>{t('Target date')}<DatePicker value={deadline} min={today} onChange={setDeadline}/></label><label>{t('Skip contribution in the month of (optional)')}<DatePicker value={missed} min={today} max={deadline||undefined} required={false} onChange={setMissed}/></label></fieldset><Button disabled={busy||goal.archived||!name.trim()||!deadline||all.length>=50}>{t('Save scenario')}</Button></form></details></>}{error&&<p role="alert">{t(error)}</p>}{guard}</section>;
}
