"use client";
import {useState} from 'react';
import {useLanguage} from '@/components/language-provider';
import {Button} from '@/components/ui/button';
import {NativeSelect} from '@/components/ui/native-select';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {DatePicker} from '@/components/date-picker';
import {FormattedNumberInput} from '@/components/formatted-number-input';
import {useUnsavedNavigation} from '@/components/discard-changes';
import {formatMoney,formatDate} from '@/lib/format';
import {fundingPlan,type GoalEvent} from '@/lib/goal-funding';
import type {Goal,PlanningData} from '@/lib/planning';
import {useOwnerResource,saveOwnerResource} from '@/hooks/use-owner-resource';
const empty={events:[] as GoalEvent[]};
type Props={data:PlanningData;currency:string;surplus:number|null;today:string;rates?:Record<string,number>;owner:string|null;demo:boolean;revision:number;onSaved:()=>void};
export function GoalFundingPanel({data,currency,surplus,today,rates,owner,demo,revision,onSaved}:Props){
 const {t,locale}=useLanguage();const activity=useOwnerResource('/api/goal-tools',owner,!demo,revision,empty);const plan=fundingPlan(data.goals,surplus,currency,today,rates);
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(action:string,payload:unknown){if(demo)throw Error(t('Sign in to save planning changes.'));setBusy(true);setError('');try{await saveOwnerResource('/api/goal-tools',action,payload);activity.invalidate();onSaved();}catch(reason){setError((reason as Error).message);throw reason;}finally{setBusy(false);}}
 const money=(value:number|null)=>value===null?'—':formatMoney(value,currency,locale);
 return <section className="panel tools-panel"><h2>{t('Shared goal funding')}</h2><p className="muted">{t('One monthly surplus funds all enabled goals in priority order. This is a plan; no money moves automatically. Enable only independent funding commitments, not overlapping net-worth targets.')}</p>
 <div className="review-grid"><article><h3>{t('Available monthly surplus')}</h3><strong>{money(surplus)}</strong></article><article><h3>{t('Planned goal funding')}</h3><strong>{money(plan.requested)}</strong></article><article><h3>{t('Combined funding shortfall')}</h3><strong className={plan.shortfall?'negative':''}>{money(plan.shortfall)}</strong></article><article><h3>{t('Unassigned monthly surplus')}</h3><strong>{money(plan.remaining)}</strong></article></div>
 {!plan.complete&&<p role="status">{t('Enter each enabled goal’s monetary budget and provide all exchange rates to complete the plan.')}</p>}
 <ul className="tool-list">{plan.rows.map(row=><li key={row.goal.id}><strong>{row.goal.name}</strong><span>{t('Funded in this plan')}: {money(row.allocated)} / {money(row.requested)}</span></li>)}</ul>
 <details><summary>{t('Priorities and monthly funding')}</summary>{data.goals.filter(goal=>!goal.archived).map(goal=><FundingEditor key={JSON.stringify(goal)} goal={goal} today={today} busy={busy||demo} save={save}/>)}</details>
 {data.goals.some(goal=>goal.kind==='savings'&&!goal.archived)&&<GoalActivityForm data={data} today={today} busy={busy||demo} save={save}/>}
 {error&&<p role="alert" className="error">{t(error)}</p>}
 <details><summary>{t('Goal activity')}</summary>{activity.error?<p role="alert">{t(activity.error)} <Button onClick={activity.retry}>{t('Retry')}</Button></p>:activity.loading?<p role="status">{t('Loading records…')}</p>:<ul className="tool-list">{activity.data.events.map(event=>{const goal=data.goals.find(goal=>goal.id===event.goal_id);return <li key={event.id}><div><strong>{goal?.name??t('Goal')}</strong><p>{formatDate(event.occurred_on,locale)} · {t(event.event_type)}{event.source_name&&` · ${event.source_name}`}</p><p>{event.event_type==='opening'?t(event.notes):event.notes}</p></div><strong>{formatMoney(Number(event.delta),goal?.currency??currency,locale)}</strong></li>;})}</ul>}</details>
 </section>;
}
function FundingEditor({goal,today,busy,save}:{goal:Goal;today:string;busy:boolean;save:(action:string,data:unknown)=>Promise<void>}){
 const {t}=useLanguage();const initial={goal_id:goal.id,priority:goal.funding_priority??100,monthly:goal.funding_monthly??null,enabled:goal.funding_enabled??false,paused_until:goal.paused_until??null,mode:goal.funding_mode??'one_time'};
 const [draft,setDraft]=useState(initial),[saved,setSaved]=useState(initial);const dirty=JSON.stringify(draft)!==JSON.stringify(saved);const guard=useUnsavedNavigation(dirty);
 return <form className="inline-tool-form" onSubmit={async event=>{event.preventDefault();try{await save('funding',draft);setSaved(draft);}catch{}}}><strong>{goal.name} · {goal.currency}</strong><fieldset className="tracker-fields" disabled={busy}><label><Checkbox checked={draft.enabled} onCheckedChange={enabled=>setDraft({...draft,enabled:enabled===true})}/>{t('Include in monthly funding')}</label><label>{t('Priority')}<FormattedNumberInput value={draft.priority} max={10000} required={false} onValueChange={priority=>setDraft({...draft,priority:priority??0})}/></label><label>{t('Monthly funding budget')}<FormattedNumberInput value={draft.monthly??0} required={false} onValueChange={monthly=>setDraft({...draft,monthly})}/></label><label>{t('Pause through')}<DatePicker value={draft.paused_until??''} min={today} required={false} onChange={value=>setDraft({...draft,paused_until:value||null})}/></label><label>{t('Goal behavior')}<NativeSelect value={draft.mode} onChange={event=>setDraft({...draft,mode:event.target.value as 'one_time'|'refill'})}><option value="one_time">{t('One-time target')}</option><option value="refill">{t('Refill after withdrawals')}</option></NativeSelect></label></fieldset><Button disabled={busy||!dirty||!Number.isInteger(draft.priority)}>{t('Save')}</Button>{guard}</form>;
}
function GoalActivityForm({data,today,busy,save}:{data:PlanningData;today:string;busy:boolean;save:(action:string,data:unknown)=>Promise<void>}){
 const {t,locale}=useLanguage();const goals=data.goals.filter(goal=>goal.kind==='savings'&&!goal.archived);const [goalId,setGoalId]=useState(goals[0]?.id??''),[type,setType]=useState('contribution'),[amount,setAmount]=useState(0),[target,setTarget]=useState(''),[source,setSource]=useState(''),[date,setDate]=useState(today),[notes,setNotes]=useState('');const [operation,setOperation]=useState<string|null>(null);const goal=goals.find(item=>item.id===goalId);const guard=useUnsavedNavigation(amount>0||!!notes);const locked=busy||!!operation;
 return <details><summary>{t('Record goal activity')}</summary><p>{t('Reserve or release money already in the account. A goal transfer changes reservations in the same account; it never transfers bank funds. Withdraw a used reservation to refill the goal later.')}</p><form className="inline-tool-form" onSubmit={async event=>{event.preventDefault();const id=operation??crypto.randomUUID();setOperation(id);try{await save('activity',{id,goal_id:goalId,target_id:type==='transfer'?target:null,source_id:type==='contribution'?source||null:null,amount,date,type,notes});setAmount(0);setNotes('');setOperation(null);}catch(reason){if((reason as {confirmedFailure?:boolean}).confirmedFailure)setOperation(null);}}}><fieldset className="tracker-fields" disabled={locked}><label>{t('Goal')}<NativeSelect value={goalId} onChange={event=>{setGoalId(event.target.value);setTarget('');setSource('');}}>{goals.map(goal=><option key={goal.id} value={goal.id}>{goal.name}</option>)}</NativeSelect></label><label>{t('Type')}<NativeSelect value={type} onChange={event=>setType(event.target.value)}>{['contribution','withdrawal','transfer'].map(value=><option key={value} value={value}>{t(value)}</option>)}</NativeSelect></label><label>{t('Amount')} {goal?.currency}<FormattedNumberInput value={amount} onValueChange={setAmount}/></label><label>{t('Date')}<DatePicker value={date} max={today} onChange={setDate}/></label>{type==='transfer'&&<label>{t('Destination goal')}<NativeSelect required value={target} onChange={event=>setTarget(event.target.value)}><option value="">{t('Select goal')}</option>{goals.filter(item=>item.id!==goalId&&item.account_id===goal?.account_id).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</NativeSelect></label>}{type==='contribution'&&<label>{t('Link income (optional)')}<NativeSelect value={source} onChange={event=>setSource(event.target.value)}><option value="">{t('None')}</option>{data.records.filter(record=>record.account_id===goal?.account_id&&record.frequency==='Once'&&['Salary','Rent income','Other income'].includes(record.kind)).map(record=><option key={record.id} value={record.id}>{record.name} · {formatMoney(record.amount,record.currency,locale)}</option>)}</NativeSelect></label>}<label>{t('Notes (optional)')}<Input value={notes} maxLength={2000} onChange={event=>setNotes(event.target.value)}/></label></fieldset><Button disabled={busy||!goal||amount<=0||type==='transfer'&&!target}>{t(operation?'Retry':'Save')}</Button>{operation&&!busy&&<Button type="button" variant="outline" onClick={()=>setOperation(null)}>{t('Edit details after checking activity')}</Button>}</form>{guard}<p className="muted">{t('Check goal activity before changing a request whose result is uncertain. Retry keeps the same operation identifier.')}</p></details>;
}
